import Footer from "@/components/ui/modiule/footer/footer";
import DeskTopMenu from "@/components/ui/modiule/Header/desktop_menu";
import { MobileNav } from "@/components/ui/modiule/Header/mobile_menu";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="w-full md:max-w-3xl lg:max-w-7xl mx-auto">
      <DeskTopMenu />
     <section className="min-h-[80vh]">
       {children}
     </section>
      <MobileNav />
      {/* footer  */}
      <Footer />
    </main>
  );
}