import type { Metadata } from "next";
import { Mona_Sans, Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({
  variable: "--font-inter",  // Use a unique name to avoid conflict
  subsets: ["latin"],
});

const monaSans = Mona_Sans({
  variable: "--font-mona",  // Use a unique name to avoid conflict
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={`${inter.variable} ${monaSans.variable}`}
    >
      <body className="antialiased font-primary bg-primary/5">{children}</body>
    </html>
  );
}